-   repo: https://github.com/pre-commit/mirrors-gradle
    rev: v0.0.7
    hooks:
      -   id: gradle
          name: Gradle spotlessApply
          entry: ./gradlew :spotlessApply
          language: system
          files: \.gradle|\.java|\.kt|\.xml|\.yml|\.yaml
